# Site settings
title: Die kleine Tigerbande
email: info@kleinetigerbande.de
description: > # this means to ignore newlines until "baseurl:"
  Die kleine Tigerbande. Tagesmutter Wiebke Potthast in Detmold.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://kleintigerbande.de" # the base hostname & protocol for your site

# User setting
owner: Wiebke Potthast
email: wiebke@kleinetigerbande.de
facebook_username: wiebke.potthast.1
#twitter_username:
#github_username: 
address:
  - line: Hildesheimer Weg 5
  - line: 32756 Detmold
  # Feel free to add more lines here 
telephone: 01515/4814256
copyright: kleinetigerbande.de

# API settings
google_api_key: AIzaSyC8MhveOesq8yBRP_Bfh-HMf-UAiGitW0Q

# Build settings
markdown: kramdown
